export const tableOption = {
  "menu": false, //不显示操作
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "主键ID",
      "prop": "id",
      "span": 12,
      "showColumn":false //表格中是否显示
    },	  {
      "type": "input",
      "label": "站点ID",
      "prop": "tenantId",
      "span": 12,
      "showColumn":false //表格中是否显示
    },	  {
      "type": "input",
      "label": "老用户ID",
      "prop": "oldUserId",
      "span": 12,
      "showColumn":false //表格中是否显示
    },	  {
      "type": "input",
      "label": "推荐用户",
      "prop": "oldUsername",
      "span": 12,
      "search": true,
      "showColumn":true //表格中是否显示
    },	  {
      "type": "input",
      "label": "新用户ID",
      "prop": "userId",
      "span": 12,
      "showColumn":false //表格中是否显示
    },	  {
      "type": "input",
      "label": "手机号",
      "prop": "phone",
      "span": 12,
      "search": true
    },	  {
      "type": "select",
      "label": "状态",
      "prop": "lockFlag",
      "span": 12,
      dicData: [{
        label: '有效',
        value: '0'
      }, {
        label: '锁定',
        value: '9'
      }],
      "search": true
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime",
      "span": 12
    },    {
      "prop": "createTimeArr",
      "span": 12,
      "type": "date",
      "label": "下单时间",
      // "searchValue": ['2021-10-21', '2021-10-22'],
      "format": "yyyy-MM-dd",
      "display": true,
      "valueFormat": "yyyy-MM-dd",
      "editDisabled": true,
      "addDisabled": true,
      "search": true,
      "searchRange": true,
      "showColumn":false //表格中是否显示
    }  ]
}
